### ISSUE TITLE
how to implement cpf_segmentation into cpf_segmentation_ros

### ISSUE THREAD

**Issue by daf11865** [MarkusEich/cpf_segmentation_ros#1]
I've got clone both, but I don't know how to set up the segmentation that is needed for cpf_segmentation_ros.
when catkin_make, it always said that segmentation module not found. could any one trying to use this package help me to figure it out?

**Comment by MarkusEich** [comment]
We will update the documentation soon. When installing the core library cpf_segmentation, make sure you do a make install (typically this will install all the libs and test programs into /usr/local/lib. Check in /usr/local/lib/pkconfig if there is a file segmentation.pc. If yes make sure that $LD_LIBRARY_PATH if pointing to /usr/local/lib and $PKG_CONFIG_PATH to /usr/local/lib/pkconfig. For testing, you can run /usr/bin/segmentation_test pointcloud.pcd for testing.

**Comment by daf11865** [comment]
@MarkusEich 
thank you! now the segmentation module is found.
$LD_LIBRARY_PATH and $PKG_CONFIG_PATH are set up, and the segmentation_test succeed.
however, the catkin_make compilation still fail. it's like the dependency version of cpf_segmentation_ros and cpf_segmentation is different, or I misunderstand it. sorry for my lack knowledge of c++ compilation.
can you help me to figure it out? thx

the error:
In file included from /usr/local/include/segmentation/segmentation.hpp:85:0,
                 from /home/daf/ROS/catkin_ws/src/cpf_segmentation_ros/src/segmentation_ros_node.cpp:44:
/usr/local/include/segmentation/segmentation_helpers.h: In function ‘bool isConvex(Eigen::Vector3f, Eigen::Vector3f, Eigen::Vector3f, Eigen::Vector3f)’:
/usr/local/include/segmentation/segmentation_helpers.h:66:73: error: too many arguments to function ‘double pcl::getAngle3D(const Vector4f&, const Vector4f&)’
  float normal_angle = pcl::getAngle3D(source_normal, target_normal, true);
                                                                         ^
In file included from /usr/include/pcl-1.7/pcl/common/common.h:194:0,
                 from /usr/include/pcl-1.7/pcl/octree/impl/octree_pointcloud.hpp:45,
                 from /usr/include/pcl-1.7/pcl/octree/octree_impl.h:46,
                 from /usr/include/pcl-1.7/pcl/octree/octree_pointcloud_adjacency.h:46,
                 from /usr/include/pcl-1.7/pcl/segmentation/supervoxel_clustering.h:49,
                 from /usr/local/include/segmentation/segmentation.hpp:61,
                 from /home/daf/ROS/catkin_ws/src/cpf_segmentation_ros/src/segmentation_ros_node.cpp:44:
/usr/include/pcl-1.7/pcl/common/impl/common.hpp:46:1: note: declared here
 pcl::getAngle3D (const Eigen::Vector4f &v1, const Eigen::Vector4f &v2)
 ^
In file included from /usr/local/include/segmentation/segmentation.hpp:85:0,
                 from /home/daf/ROS/catkin_ws/src/cpf_segmentation_ros/src/segmentation_ros_node.cpp:44:
/usr/local/include/segmentation/segmentation_helpers.h:97:70: error: too many arguments to function ‘double pcl::getAngle3D(const Vector4f&, const Vector4f&)’
 float intersection_angle =  pcl::getAngle3D (ncross, vec_t_to_s, true);
                                                                      ^
In file included from /usr/include/pcl-1.7/pcl/common/common.h:194:0,
                 from /usr/include/pcl-1.7/pcl/octree/impl/octree_pointcloud.hpp:45,
                 from /usr/include/pcl-1.7/pcl/octree/octree_impl.h:46,
                 from /usr/include/pcl-1.7/pcl/octree/octree_pointcloud_adjacency.h:46,
                 from /usr/include/pcl-1.7/pcl/segmentation/supervoxel_clustering.h:49,
                 from /usr/local/include/segmentation/segmentation.hpp:61,
                 from /home/daf/ROS/catkin_ws/src/cpf_segmentation_ros/src/segmentation_ros_node.cpp:44:
/usr/include/pcl-1.7/pcl/common/impl/common.hpp:46:1: note: declared here
 pcl::getAngle3D (const Eigen::Vector4f &v1, const Eigen::Vector4f &v2)
 ^
In file included from /usr/include/eigen3/Eigen/Core:254:0,
                 from /usr/include/eigen3/Eigen/StdVector:14,
                 from /usr/include/pcl-1.7/pcl/pcl_base.h:49,
                 from /usr/include/pcl-1.7/pcl/filters/filter.h:43,
                 from /home/daf/ROS/catkin_ws/src/cpf_segmentation_ros/src/segmentation_ros_node.cpp:38:
/usr/include/eigen3/Eigen/src/Core/Assign.h: In instantiation of ‘Derived& Eigen::DenseBase<Derived>::lazyAssign(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Matrix<float, 3, 1>; Derived = Eigen::Matrix<float, 4, 1>]’:
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:411:46:   required from ‘Derived& Eigen::PlainObjectBase<Derived>::lazyAssign(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Matrix<float, 3, 1>; Derived = Eigen::Matrix<float, 4, 1>]’
/usr/include/eigen3/Eigen/src/Core/Assign.h:520:123:   required from ‘static Derived& Eigen::internal::assign_selector<Derived, OtherDerived, false, false>::run(Derived&, const OtherDerived&) [with Derived = Eigen::Matrix<float, 4, 1>; OtherDerived = Eigen::Matrix<float, 3, 1>]’
/usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:618:105:   required from ‘Derived& Eigen::PlainObjectBase<Derived>::_set_noalias(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Matrix<float, 3, 1>; Derived = Eigen::Matrix<float, 4, 1>]’
/usr/include/eigen3/Eigen/src/Core/Matrix.h:281:31:   required from ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const Eigen::MatrixBase<OtherDerived>&) [with OtherDerived = Eigen::Matrix<float, 3, 1>; _Scalar = float; int _Rows = 4; int _Cols = 1; int _Options = 0; int _MaxRows = 4; int _MaxCols = 1]’
/usr/local/include/segmentation/segmentation_helpers.h:66:73:   required from here
/usr/include/eigen3/Eigen/src/Core/Assign.h:492:3: error: ‘YOU_MIXED_MATRICES_OF_DIFFERENT_SIZES’ is not a member of ‘Eigen::internal::static_assertion<false>’
   EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE(Derived,OtherDerived)
   ^
make[2]: **\* [cpf_segmentation_ros/CMakeFiles/segmentation_ros_node.dir/src/segmentation_ros_node.cpp.o] Error 1
make[1]: **\* [cpf_segmentation_ros/CMakeFiles/segmentation_ros_node.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by MarkusEich** [comment]
This seems to be an issue with your PCL installation. cpf segmentation depends on PCL 1.8 so you might need to install this version from github.
